<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="GLB-343-PC" failures="2" tests="8" name="Test" time="0.087" errors="0" timestamp="09 Oct 2018 06:28:20 GMT">
  <testcase classname="RetryTest.MyTest" name="test01" time="0.017">
    <skipped/>
  </testcase> <!-- test01 -->
  <testcase classname="RetryTest.MyTest" name="test01" time="0.001">
    <skipped/>
  </testcase> <!-- test01 -->
  <testcase classname="RetryTest.MyTest" name="test01" time="0.002">
    <skipped/>
  </testcase> <!-- test01 -->
  <testcase classname="RetryTest.MyTest" name="test01" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at RetryTest.MyTest.test01(MyTest.java:15)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test01 -->
  <testcase classname="RetryTest.MyTest" name="test02" time="0.002">
    <skipped/>
  </testcase> <!-- test02 -->
  <testcase classname="RetryTest.MyTest" name="test02" time="0.001">
    <skipped/>
  </testcase> <!-- test02 -->
  <testcase classname="RetryTest.MyTest" name="test02" time="0.002">
    <skipped/>
  </testcase> <!-- test02 -->
  <testcase classname="RetryTest.MyTest" name="test02" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RetryTest.MyTest.test02(MyTest.java:21)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test02 -->
</testsuite> <!-- Test -->
